#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_WIDTH_BLOCKS 32
#define WINDOW_HEIGHT_BLOCKS 18
#define WINDOW_WIDTH_PIXELS WINDOW_WIDTH_BLOCKS * 16
#define WINDOW_HEIGHT_PIXELS WINDOW_HEIGHT_BLOCKS * 16
#define WINDOW_WIDTH_PIXELS_F 512.0f
#define WINDOW_HEIGHT_PIXELS_F 288.0f

#endif // CONFIG_H